FROM python:3.9

# Allows docker to cache installed dependencies between builds
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Mounts the application code to the image
COPY . app
WORKDIR /app
EXPOSE 8000

COPY .env.local /app/.env.local

ENTRYPOINT ["python", "manage.py"]
CMD ["migrate"]
CMD ["runserver", "0.0.0.0:8000"]
