#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

postgres_ready() {
python << END
import sys

import psycopg2
import os
def check_postgres_connection():
    dbname = "selteqtask_db"
    user = "postgres"
    password = "123"
    host = "postgres"
    port = "5432"

    try:
        psycopg2.connect(
            dbname=dbname,
            user=user,
            password=password,
            host=host,
            port=port
        )
    except psycopg2.OperationalError as e:
       print(f"Error connecting to PostgreSQL: {e}", file=sys.stderr)
       return False

if not check_postgres_connection():
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
